name: Terraform CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - "07-iac-ci-cd-pipeline/**"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: 07-iac-ci-cd-pipeline/terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: 07-iac-ci-cd-pipeline/terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: 07-iac-ci-cd-pipeline/terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: 07-iac-ci-cd-pipeline/terraform
        run: terraform apply -auto-approve

